version: '3.9'

services:
  db:
    container_name: boilerplate-db
    image: mysql:8.0.39
    restart: always
    environment:
      MYSQL_DATABASE: boilerplate
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"